apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsconfig
  labels:
    app: devopsconfig
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: devopsconfig
  template:
    metadata:
      labels:
        app: devopsconfig
    spec:
      containers:
      - name: devopspipeline
        image: lalith425/devopspipeline@sha256:cc439d30d0b733c3cabd542111b3c48d8fcb2095f669bc342ac0b82a1e2948dc
        ports:
        - containerPort: 9090
